title: JotLang
description: A melhor amiga do backend
baseurl: "/JotLang"
url: "https://jotamath.github.io"

# Build settings
markdown: kramdown
theme: just-the-docs
remote_theme: just-the-docs/docs

# Aux links for the upper right navigation
aux_links:
  "JotLang no GitHub":
    - "//github.com/jotamath/JotLang"

# Enable or disable the site search
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

# Footer content
footer_content: "Copyright &copy; 2024 JotLang. Distribuído sob a licença MIT."

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      search: true

# Configurações de navegação
nav_external_links:
  - title: Jot Lang no GitHub
    url: https://github.com/seu-usuario/jotlang
    hide_icon: false

# Configurações de back to top
back_to_top: true
back_to_top_text: "Voltar ao topo" 