source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-theme-cayman"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-seo-tag", "~> 2.8.0"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end 